apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: nginx
      version: '9.6.1'
  interval: 20s
  releaseName: nginx-9.6.1


  # dependencies:
  # - name: nginx
  #   version: 9.6.1
  #   repository: https://charts.bitnami.com/bitnami
  #   dependsOn:
    # - name: infrastructure